services:
  - type: web
    name: iba-real-estate
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node newapp.js
    envVars:
      - key: DB_HOST
        value: mysql-74c581-ibarealestate.i.aivencloud.com
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_7legHqlZHFCO9Evp2Hz
      - key: DB_DATABASE
        value: iba_real_estate
      - key: DB_PORT
        value: "20346" # Quotes are needed because it's a number
