services:
  - type: web
    name: iba-real-estate
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node newapp.js
    envVars:
      - key: mysql-74c581-ibarealestate.i.aivencloud.com
        sync: false # You will set this in the dashboard
      - key: avnadmin
        sync: false
      - key: AVNS_7legHqlZHFCO9Evp2Hz
        sync: false
      - key: iba_real_estate
        sync: false
      - key: 20346
        sync: false
